### ISSUE TITLE
Ajouter la commune dans la liste des infos renvoyés

### ISSUE THREAD

**Issue by gbertherat** [adriens/opt-temps-attente-agences-sdk#16]
Dans le JSON qui est renvoyé par le endpoint ```/temps-attente/agences```, ajouter une entrée pour la commune de l'agence si possible. La commune peut être trouvé dans la partie "localité" de open-data.opt.nc (voir bas de l'image qui suit)

![image](https://user-images.githubusercontent.com/61923651/101122323-5107ac00-3646-11eb-879c-7d7581715a39.png)

Éventuellement ajouter le code postal aussi, si juger nécessaire.

Merci!

**Comment by adriens** [comment]
Excellente idée, je propose même en fait de rajouter les champs suivants:

- [ ] `type`
- [ ] `codeESirius`
- [ ] `idRefLoc`
- [ ] `codePostalRefloc`
- [ ] `codePostal`
- [ ] `lieuDitOuTribu`
- [ ] `localiteRefloc`
- [ ] `localite`

**Comment by HakumenNC** [comment]
* [x]  `type`
* [x]  `codeESirius`
* [x]  `idRefLoc`
* [x]  `codePostalRefloc`
* [x]  `codePostal`
* [x]  `lieuDitOuTribu`
* [x]  `localiteRefloc`
* [x]  `localite`

✔️

**Comment by adriens** [comment]
👏 Efficace 🚀
